### ISSUE TITLE
Finding out if a person is a boy & girl by ID number

### ISSUE THREAD

**Issue by EXELANCE-LLC** [elmsec/Turkish_IDs#3]
**Is it possible to find out if a person is a boy & girl by ID number? Is there an algorithm for this process or is there a formula you recommend?**

**Comment by elmsec** [comment]
I believe that there isn't a suitable algorithm for that. It would raise some privacy concerns.

**Comment by EXELANCE-LLC** [comment]
hmmm... It's an interesting topic actually. I'm going to do some research on this and see whether the numbers are rigged or not. I'll let you know if I find anything.

**Comment by Qeyf** [comment]
> I believe that there isn't a suitable algorithm for that. It would raise some privacy concerns.

hmmm... It's an interesting topic actually. I'm going to do some research on this and see whether the numbers are rigged or not. I'll let you know if I find anything.
